
database:
    type: postgresql:16
    disk: 1024


varnish:
    type: varnish:6.0
    relationships:
        application: 'app:http'
    configuration:
        vcl: !include
            type: string
            path: config.vcl

files:
    type: network-storage:2.0
    disk: 256

rediscache:
    type: redis:5.0

queue:
    type: rabbitmq:3.7
    disk: 1024
    size: S
